config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # index  - products_path
  # new    - new_product_path
  # edit   - edit_product_path
  # show   - product_path
  # create - n/a
  # update - n/a
  # destroy - n/a

  get '/', to: 'welcome#home', as: 'home'

  # # IDEAS
  # # index
  # get '/ideas', to: 'ideas#index', as: 'ideas'
  # # new
  # get '/ideas/new', to: 'ideas#new', as: 'new_idea'
  # # create
  # post '/ideas', to: 'ideas#create'
  # # show
  # get '/ideas/:id', to: 'ideas#show', as: 'idea'
  # # edit
  # get '/ideas/:id/edit', to: 'ideas#edit', as: 'edit_idea'
  # # update
  # patch '/ideas/:id', to: 'ideas#update'
  # # delete
  # delete '/ideas/:id', to: 'ideas#destroy'

  resources :ideas do
    resources :reviews, only:[:create, :destroy]
  end

  resources :users, only:[:new, :create]

  resources :sessions, only:[:new, :create]

  delete '/sessions', to: 'sessions#destroy'



end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    alias_action(:create, :read, :update, :delete, to: :crud)
    can(:crud, Idea) do |idea|
      user == idea.user
    end

    can(:crud, Review) do |review|
      user == review.user
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord

    has_many :reviews
    belongs_to :user, optional: true

    validates :title, presence: true    # , uniqueness: true

    before_save :capitalize_title


    private

    def capitalize_title
        self.title.capitalize!
    end

end

app/models/review.rb
class Review < ApplicationRecord

    belongs_to :idea
    belongs_to :user, optional: true

    validates :rating, presence: { message: 'Please select a rating' }, length: { minimum: 1, maximum: 5 }

end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    has_many :ideas, dependent: :nullify
    has_many :reviews, dependent: :nullify


    
    def full_name
        "#{first_name} #{last_name}"
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def current_user
        @current_user ||= User.find_by_id session[:user_id]
    end

    helper_method :current_user

    def user_signed_in?
        current_user.present?
    end

    helper_method :user_signed_in?

    def authenticate_user!
        redirect_to new_session_path, notice: 'Please sign in' unless user_signed_in?
    end
    
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

    before_action :authorize_user!, only:[:edit, :update, :destroy]
    before_action :authenticate_user!, except:[:index, :show]
    before_action :find_idea, only: [:show, :edit, :update, :destroy]

    def new
        @idea = Idea.new
    end

    def create
        @idea = Idea.new idea_params
        @idea.user = current_user
        
        if @idea.save
            flash[:notice] = "Idea created successfully"
            redirect_to @idea       # same as: idea_path(@idea)
        else
            render :new
        end
    end

    def show
        @review = Review.new
        @reviews = @idea.reviews.order(created_at: :desc)
    end

    def index
        @ideas = Idea.all.order(created_at: :desc)
    end

    # def edit

    # end

    def update
        if @idea.update idea_params
            redirect_to idea_path(@idea)
        else
            render :edit
        end
    end

    def destroy
        @idea.destroy
        redirect_to ideas_path
    end


    private

    def idea_params
        params.require(:idea).permit(:title, :body)
    end

    def find_idea
        @idea = Idea.find params[:id]
    end

    def authorize_user!
        redirect_to home_path, alert: 'Not Authorized' unless can?(:crud, Idea)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :authenticate_user!, except:[:index, :show]
    before_action :find_idea, only:[:create, :destroy]
    before_action :authorize_user!, only:[:edit, :update, :destroy]

    def create
        @review = Review.new review_params
        @review.idea = @idea
        @review.user = current_user

        if @review.save
            redirect_to idea_path(@idea, @review), notice: 'Review Created'
        else
            @reviews = @idea.reviews.order(created_at: :desc)
            render '/ideas/show'
        end
    end

    def destroy
        @review = Review.find params[:id]
        if can? :crud, @review
            @review.destroy
            redirect_to idea_path(@idea, @review), notice: 'Review Deleted'
        else
            redirect_to home_path, alert: 'Not Authorized!'
        end
    end


    private

    def find_idea
        @idea = Idea.find params[:idea_id]
    end

    def review_params
        params.require(:review).permit(:body, :rating)
    end

    def authorize_user!
        redirect_to home_path, alert: 'Not Authorized' unless can? :crud, @idea
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new

    end

    def create
        @user = User.find_by_email params[:email]
        if @user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to home_path, notice: 'Logged in'
        else
            flash[:alert] = "Wrong email or password"
            render :new
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to home_path, notice: 'Signed out'
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create 
        @user = User.new user_params
        if @user.save
            session[:user_id] = @user.id
            redirect_to home_path, notice: "Logged in!"
        else
            render :new
        end
    end

    def user_params
        params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def home
    
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ideas/edit.html.erb
<h1>Edit Page</h1>
<h2>Url: /ideas/edit</h2>

<%= form_for @idea do |form| %>
    <% if @idea.errors.present? %>
        <p><%= @idea.errors.full_messages.join(', ') %></p>
    <% end %>

    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :body %>
        <%= form.text_field :body %>
    </div>

    <%= form.submit %>

<% end %>

app/views/ideas/index.html.erb
<h1>Index Page</h1>
<h2>Url: /ideas/index</h2>

<% @ideas.each do |idea| %>
    <div>
        <h3><%= link_to idea.title, idea_path(idea) %></h3>
        <p><%= idea.body %></p>
    </div>
<% end %>

app/views/ideas/new.html.erb
<h1>New Page</h1>
<h2>Url: /ideas/new</h2>

<%= form_for @idea do |form| %>
    <% if @idea.errors.present? %>
        <p><%= @idea.errors.full_messages.join(', ') %></p>
    <% end %>

    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :body %>
        <%= form.text_field :body %>
    </div>

    <%= form.submit %>

<% end %>

app/views/ideas/show.html.erb
<h1>Show Page</h1>
<h2>Url: /ideas/show</h2>

<h3><%= @idea.title %></h3>
<h4><%= @idea.body %></h4>
<h5>Created By: <%= @idea.user&.full_name || 'DELETED' %></h5>
<p><strong>Created At:</strong><%= @idea.created_at %></p>
<p><strong>Updated At:</strong><%= @idea.updated_at %></p>
<% if can?(:crud, @idea) %>
    <%= link_to 'Edit', edit_idea_path(@idea) %>
    <%= link_to 'Delete', idea_path(@idea), method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

<%= render 'reviews/form' %>

<% @reviews.each do |review| %>
    <%= review.rating %>
    <%= review.body %>
    <small><%= time_ago_in_words(review.created_at) %></small><br>
    <small>Reviewed By: <%= review.user&.full_name || 'Deleted' %></small><br>
    <% if can? :crud, review %>
        <%= button_to('Delete', idea_review_path(@idea, review),
                        method: :delete, data:{confirm: 'Are you sure?'}) %>
    <% end %>
    <hr>
    
<% end %>

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', home_path %>
<%= link_to 'Ideas', ideas_path %>
<%= link_to 'New Idea', new_idea_path %>

<% if user_signed_in? %>
    Hello <%= current_user.full_name %> | <%= link_to 'Logout', sessions_path, method: :delete, data:{ confirm: 'Are you sure you want to logout?' } %>
<% else %>
    <%= link_to 'Login', new_session_path %>
    <%= link_to 'Sign Up', new_user_path %>
<% end %>

<hr>
<%= flash[:notice] || flash[:alert] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaFactory</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>

  <%= render 'layouts/navbar' %>
  
  <%= flash[:notice] || flash[:alert] %>

    <%= yield %>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_with(model:[@idea, @review], local:true) do |f| %>

    <% if @review.errors.full_messages.each do |msg| %>
        <ul>
            <li><%= msg %></li>
        </ul>
    <% end; end %>

    <p>Reviews:</p>
    
    <div>
        <%= f.select(:rating, options_for_select(1..5)) %>
    </div>

    <div>
        <%= f.text_area(:body,
                        cols: 50,
                        rows: 5,
                        placeholder: 'What is your review?') %>
    </div>

    <%= f.submit 'Review' %>

<% end %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<h2>Url: users/new</h2>
<%= form_with model:@user, local: true do |f| %>
    <div>
        <%= f.label :first_name %>
        <%= f.text_field :first_name %>
    </div>

    <div>
        <%= f.label :last_name %>
        <%= f.text_field :last_name %>
    </div>

    <div>
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>

    <div>
        <%= f.label :password %>
        <%= f.password_field :password %>
    </div>

    <div>
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation %>
    </div>

    <%= f.submit 'Sign Up' %>

<% end %>

app/views/welcome/home.html.erb
<h1>Welcome Page</h1>
<h2>Url: /</h2>